# Generated by Django 4.2.4 on 2023-08-08 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sismos", "0002_sismo_depth_km_sismo_geo_reference_sismo_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sismo",
            old_name="depth_km",
            new_name="latitud",
        ),
        migrations.RenameField(
            model_name="sismo",
            old_name="latitude",
            new_name="longitud",
        ),
        migrations.RemoveField(
            model_name="sismo",
            name="geo_reference",
        ),
        migrations.RemoveField(
            model_name="sismo",
            name="local_date",
        ),
        migrations.RemoveField(
            model_name="sismo",
            name="longitude",
        ),
    ]
